spring.application.name=admin

spring.datasource.url=jdbc:postgresql://10.241.29.52:5432/java
spring.datasource.username=postgres
spring.datasource.password=KxfOwrJY3V
spring.datasource.generate-unique-name=false
spring.datasource.name=java

spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

